
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Mar 02 11:46:24 CET 2017
//----------------------------------------------------

package mini_c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int SIZEOF = 8;
  public static final int AND = 14;
  public static final int IDENT = 28;
  public static final int ELSE = 5;
  public static final int IFTHEN = 21;
  public static final int PLUS = 15;
  public static final int STRUCT = 3;
  public static final int OR = 13;
  public static final int INT = 9;
  public static final int LP = 26;
  public static final int EQUAL = 12;
  public static final int WHILE = 6;
  public static final int RP = 25;
  public static final int FLECHE = 11;
  public static final int NOT = 19;
  public static final int RETURN = 7;
  public static final int IF = 4;
  public static final int LA = 24;
  public static final int COMMA = 27;
  public static final int RA = 23;
  public static final int CST = 2;
  public static final int SEMICOLUMN = 22;
  public static final int EOF = 0;
  public static final int CMP = 10;
  public static final int DIV = 18;
  public static final int MINUS = 16;
  public static final int error = 1;
  public static final int UMINUS = 20;
}

